//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodStallEFVersion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.TransLogs = new HashSet<TransLog>();
        }
    
        public int orderID { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public string deliveryLocation { get; set; }
        public string orderStatus { get; set; }
        public string orderUser { get; set; }
        public string orderDish { get; set; }
        public string orderSize { get; set; }
        public string orderSpices { get; set; }
    
        public virtual Food_Dish Food_Dishes { get; set; }
        public virtual Size Size { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransLog> TransLogs { get; set; }
    }
}
