//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodStallEFVersion
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransLog
    {
        public int logId { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string action { get; set; }
        public string userName { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
    }
}
